# https://packaging.python.org/en/latest/tutorials/packaging-projects/

[build-system]
requires = ['setuptools>=68.0']
build-backend = 'setuptools.build_meta'

[tool.setuptools.packages.find]
where = ['.']

[project]
name = 'webutil'
version = '0.1'
authors = [
    { name='Ryan Barrett', email='webutil@ryanb.org' },
]
description = 'Common utilities and handler code for Python web apps'
readme = 'README.md'
requires-python = '>=3.7'
keywords = ['App Engine', 'Flask', 'HTTP', 'web', 'utilities']
dependencies = [
    'cachetools>=3.1',
    'domain2idna>=1.12',
    'Flask>=2.0',
    'google-cloud-ndb>=2.0',
    'humanize==4.12.0',
    'mf2util>=0.5.0',
    'werkzeug',
]

# https://pypi.org/classifiers/
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: Public Domain',
    'Operating System :: OS Independent',
    'Intended Audience :: Developers',
    'Development Status :: 4 - Beta',
    'Topic :: Software Development :: Libraries :: Python Modules',
]

[project.urls]
'Homepage' = 'https://github.com/snarfed/webutil'
'Documentation' = 'https://oauth-dropins.readthedocs.io/en/latest/source/oauth_dropins.webutil.html'

[project.optional-dependencies]
tests = [
    'mox3>=0.28,<2.0',
    'beautifulsoup4>=4.8',
]
